# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_commit]
disabled = false
commit_hash_length = 7
# prefix="at commit #"
# suffix=""

[hostname]
ssh_only = false
disabled = false

[kubernetes]
symbol = "⛵ "
style = "dim green"
disabled = false

[docker_context]
disabled = false
